-- Generate random availability (true or false) for each date from April 1 to May 31
INSERT INTO Rooms (TypeID, ThemeName, BedType, Date, IsAvailable, Price)
SELECT
    TypeID, 
    ThemeName,
    BedType,
    dates.Date,
    CASE WHEN ROUND(RAND()) = 0 THEN FALSE ELSE TRUE END AS IsAvailable,
    Price
FROM
    Rooms,
    (SELECT DATE_ADD('2024-04-01', INTERVAL t0.i + t1.i*10 + t2.i*100 DAY) AS Date
     FROM
         (SELECT 0 AS i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS t0,
         (SELECT 0 AS i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS t1,
         (SELECT 0 AS i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) AS t2
     WHERE DATE_ADD('2024-04-01', INTERVAL t0.i + t1.i*10 + t2.i*100 DAY) <= '2024-05-31') AS dates
WHERE dates.Date >= '2024-04-01' AND dates.Date <= '2024-05-31';
